default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
 
primary: &primary
  <<: *default
  database: storage/<%= Rails.env %>.sqlite3
 
queue: &queue
  <<: *default
  migrations_paths: db/queue/migrate
  database: storage/queue.sqlite3

cache: &cache
  <<: *default
  migrations_paths: db/cache/migrate
  database: storage/cache.sqlite3

development:
  primary: *primary
  queue: *queue
  cache: *cache
 
test:
  <<: *primary
  database: db/test.sqlite3
 
production:
  primary: *primary
  queue: *queue
  cache: *cache